/*
* generated by Xtext
*/
package org.xtext.rollercoaster.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.rollercoaster.dsl.services.CoasterGrammarAccess;

public class CoasterParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CoasterGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.rollercoaster.dsl.parser.antlr.internal.InternalCoasterParser createParser(XtextTokenStream stream) {
		return new org.xtext.rollercoaster.dsl.parser.antlr.internal.InternalCoasterParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public CoasterGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CoasterGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
