/*
* generated by Xtext
*/
package org.xtext.rollercoaster.dsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class CoasterGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Assignment cRollerCoasterAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cRollerCoasterRollerCoasterParserRuleCall_0 = (RuleCall)cRollerCoasterAssignment.eContents().get(0);
		
		//Model:
		//	rollerCoaster+=RollerCoaster;
		public ParserRule getRule() { return rule; }

		//rollerCoaster+=RollerCoaster
		public Assignment getRollerCoasterAssignment() { return cRollerCoasterAssignment; }

		//RollerCoaster
		public RuleCall getRollerCoasterRollerCoasterParserRuleCall_0() { return cRollerCoasterRollerCoasterParserRuleCall_0; }
	}

	public class RollerCoasterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RollerCoaster");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRollerCoasterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cTrackAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cTrackAlternatives_2_0 = (Alternatives)cTrackAssignment_2.eContents().get(0);
		private final RuleCall cTrackStraightParserRuleCall_2_0_0 = (RuleCall)cTrackAlternatives_2_0.eContents().get(0);
		private final RuleCall cTrackCornerParserRuleCall_2_0_1 = (RuleCall)cTrackAlternatives_2_0.eContents().get(1);
		private final Assignment cCartAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCartCartParserRuleCall_3_0 = (RuleCall)cCartAssignment_3.eContents().get(0);
		private final Assignment cTrackUnitLengthAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTrackUnitLengthINTTerminalRuleCall_4_0 = (RuleCall)cTrackUnitLengthAssignment_4.eContents().get(0);
		
		//RollerCoaster:
		//	"RollerCoaster" name=ID track+=(Straight | Corner)* cart+=Cart* trackUnitLength=INT;
		public ParserRule getRule() { return rule; }

		//"RollerCoaster" name=ID track+=(Straight | Corner)* cart+=Cart* trackUnitLength=INT
		public Group getGroup() { return cGroup; }

		//"RollerCoaster"
		public Keyword getRollerCoasterKeyword_0() { return cRollerCoasterKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//track+=(Straight | Corner)*
		public Assignment getTrackAssignment_2() { return cTrackAssignment_2; }

		//Straight | Corner
		public Alternatives getTrackAlternatives_2_0() { return cTrackAlternatives_2_0; }

		//Straight
		public RuleCall getTrackStraightParserRuleCall_2_0_0() { return cTrackStraightParserRuleCall_2_0_0; }

		//Corner
		public RuleCall getTrackCornerParserRuleCall_2_0_1() { return cTrackCornerParserRuleCall_2_0_1; }

		//cart+=Cart*
		public Assignment getCartAssignment_3() { return cCartAssignment_3; }

		//Cart
		public RuleCall getCartCartParserRuleCall_3_0() { return cCartCartParserRuleCall_3_0; }

		//trackUnitLength=INT
		public Assignment getTrackUnitLengthAssignment_4() { return cTrackUnitLengthAssignment_4; }

		//INT
		public RuleCall getTrackUnitLengthINTTerminalRuleCall_4_0() { return cTrackUnitLengthINTTerminalRuleCall_4_0; }
	}

	public class StraightElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Straight");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStraightKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cLengthAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLengthINTTerminalRuleCall_2_0 = (RuleCall)cLengthAssignment_2.eContents().get(0);
		private final Assignment cElevationChangeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cElevationChangeINTTerminalRuleCall_3_0 = (RuleCall)cElevationChangeAssignment_3.eContents().get(0);
		
		//Straight:
		//	"Straight" name=ID length=INT elevationChange=INT?;
		public ParserRule getRule() { return rule; }

		//"Straight" name=ID length=INT elevationChange=INT?
		public Group getGroup() { return cGroup; }

		//"Straight"
		public Keyword getStraightKeyword_0() { return cStraightKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//length=INT
		public Assignment getLengthAssignment_2() { return cLengthAssignment_2; }

		//INT
		public RuleCall getLengthINTTerminalRuleCall_2_0() { return cLengthINTTerminalRuleCall_2_0; }

		//elevationChange=INT?
		public Assignment getElevationChangeAssignment_3() { return cElevationChangeAssignment_3; }

		//INT
		public RuleCall getElevationChangeINTTerminalRuleCall_3_0() { return cElevationChangeINTTerminalRuleCall_3_0; }
	}

	public class CornerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Corner");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCornerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDirectionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cDirectionAlternatives_2_0 = (Alternatives)cDirectionAssignment_2.eContents().get(0);
		private final Keyword cDirectionLeftKeyword_2_0_0 = (Keyword)cDirectionAlternatives_2_0.eContents().get(0);
		private final Keyword cDirectionRightKeyword_2_0_1 = (Keyword)cDirectionAlternatives_2_0.eContents().get(1);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Alternatives cTypeAlternatives_3_0 = (Alternatives)cTypeAssignment_3.eContents().get(0);
		private final Keyword cTypeSharp45Keyword_3_0_0 = (Keyword)cTypeAlternatives_3_0.eContents().get(0);
		private final Keyword cTypeSharp90Keyword_3_0_1 = (Keyword)cTypeAlternatives_3_0.eContents().get(1);
		private final Keyword cTypeEasy45Keyword_3_0_2 = (Keyword)cTypeAlternatives_3_0.eContents().get(2);
		private final Keyword cTypeEasy90Keyword_3_0_3 = (Keyword)cTypeAlternatives_3_0.eContents().get(3);
		
		//Corner:
		//	"Corner" name=ID direction=("left" | "right") type=("sharp45" | "sharp90" | "easy45" | "easy90");
		public ParserRule getRule() { return rule; }

		//"Corner" name=ID direction=("left" | "right") type=("sharp45" | "sharp90" | "easy45" | "easy90")
		public Group getGroup() { return cGroup; }

		//"Corner"
		public Keyword getCornerKeyword_0() { return cCornerKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//direction=("left" | "right")
		public Assignment getDirectionAssignment_2() { return cDirectionAssignment_2; }

		//"left" | "right"
		public Alternatives getDirectionAlternatives_2_0() { return cDirectionAlternatives_2_0; }

		//"left"
		public Keyword getDirectionLeftKeyword_2_0_0() { return cDirectionLeftKeyword_2_0_0; }

		//"right"
		public Keyword getDirectionRightKeyword_2_0_1() { return cDirectionRightKeyword_2_0_1; }

		//type=("sharp45" | "sharp90" | "easy45" | "easy90")
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }

		//"sharp45" | "sharp90" | "easy45" | "easy90"
		public Alternatives getTypeAlternatives_3_0() { return cTypeAlternatives_3_0; }

		//"sharp45"
		public Keyword getTypeSharp45Keyword_3_0_0() { return cTypeSharp45Keyword_3_0_0; }

		//"sharp90"
		public Keyword getTypeSharp90Keyword_3_0_1() { return cTypeSharp90Keyword_3_0_1; }

		//"easy45"
		public Keyword getTypeEasy45Keyword_3_0_2() { return cTypeEasy45Keyword_3_0_2; }

		//"easy90"
		public Keyword getTypeEasy90Keyword_3_0_3() { return cTypeEasy90Keyword_3_0_3; }
	}

	public class CartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Cart");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Cart:
		//	"Cart" name=ID;
		public ParserRule getRule() { return rule; }

		//"Cart" name=ID
		public Group getGroup() { return cGroup; }

		//"Cart"
		public Keyword getCartKeyword_0() { return cCartKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}

	public class SignedIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SignedInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSignAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cSignHyphenMinusKeyword_0_0 = (Keyword)cSignAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//SignedInt:
		//	sign="-"? value=INT;
		public ParserRule getRule() { return rule; }

		//sign="-"? value=INT
		public Group getGroup() { return cGroup; }

		//sign="-"?
		public Assignment getSignAssignment_0() { return cSignAssignment_0; }

		//"-"
		public Keyword getSignHyphenMinusKeyword_0_0() { return cSignHyphenMinusKeyword_0_0; }

		//value=INT
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_1_0() { return cValueINTTerminalRuleCall_1_0; }
	}
	
	
	private ModelElements pModel;
	private RollerCoasterElements pRollerCoaster;
	private StraightElements pStraight;
	private CornerElements pCorner;
	private CartElements pCart;
	private SignedIntElements pSignedInt;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public CoasterGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.rollercoaster.dsl.Coaster".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	rollerCoaster+=RollerCoaster;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//RollerCoaster:
	//	"RollerCoaster" name=ID track+=(Straight | Corner)* cart+=Cart* trackUnitLength=INT;
	public RollerCoasterElements getRollerCoasterAccess() {
		return (pRollerCoaster != null) ? pRollerCoaster : (pRollerCoaster = new RollerCoasterElements());
	}
	
	public ParserRule getRollerCoasterRule() {
		return getRollerCoasterAccess().getRule();
	}

	//Straight:
	//	"Straight" name=ID length=INT elevationChange=INT?;
	public StraightElements getStraightAccess() {
		return (pStraight != null) ? pStraight : (pStraight = new StraightElements());
	}
	
	public ParserRule getStraightRule() {
		return getStraightAccess().getRule();
	}

	//Corner:
	//	"Corner" name=ID direction=("left" | "right") type=("sharp45" | "sharp90" | "easy45" | "easy90");
	public CornerElements getCornerAccess() {
		return (pCorner != null) ? pCorner : (pCorner = new CornerElements());
	}
	
	public ParserRule getCornerRule() {
		return getCornerAccess().getRule();
	}

	//Cart:
	//	"Cart" name=ID;
	public CartElements getCartAccess() {
		return (pCart != null) ? pCart : (pCart = new CartElements());
	}
	
	public ParserRule getCartRule() {
		return getCartAccess().getRule();
	}

	//SignedInt:
	//	sign="-"? value=INT;
	public SignedIntElements getSignedIntAccess() {
		return (pSignedInt != null) ? pSignedInt : (pSignedInt = new SignedIntElements());
	}
	
	public ParserRule getSignedIntRule() {
		return getSignedIntAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
