/*
* generated by Xtext
*/
package org.xtext.rollercoaster.dsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class CoasterGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Assignment cRollerCoasterAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cRollerCoasterRollerCoasterParserRuleCall_0 = (RuleCall)cRollerCoasterAssignment.eContents().get(0);
		
		//Model:
		//	rollerCoaster+=RollerCoaster;
		public ParserRule getRule() { return rule; }

		//rollerCoaster+=RollerCoaster
		public Assignment getRollerCoasterAssignment() { return cRollerCoasterAssignment; }

		//RollerCoaster
		public RuleCall getRollerCoasterRollerCoasterParserRuleCall_0() { return cRollerCoasterRollerCoasterParserRuleCall_0; }
	}

	public class RollerCoasterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RollerCoaster");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cTrackAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTrackTrackParserRuleCall_1_0 = (RuleCall)cTrackAssignment_1.eContents().get(0);
		private final Assignment cCartAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCartCartParserRuleCall_2_0 = (RuleCall)cCartAssignment_2.eContents().get(0);
		
		//RollerCoaster:
		//	name=ID track+=Track* cart+=Cart*;
		public ParserRule getRule() { return rule; }

		//name=ID track+=Track* cart+=Cart*
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//track+=Track*
		public Assignment getTrackAssignment_1() { return cTrackAssignment_1; }

		//Track
		public RuleCall getTrackTrackParserRuleCall_1_0() { return cTrackTrackParserRuleCall_1_0; }

		//cart+=Cart*
		public Assignment getCartAssignment_2() { return cCartAssignment_2; }

		//Cart
		public RuleCall getCartCartParserRuleCall_2_0() { return cCartCartParserRuleCall_2_0; }
	}

	public class TrackElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Track");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTrackKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cLengthAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLengthINTTerminalRuleCall_2_0 = (RuleCall)cLengthAssignment_2.eContents().get(0);
		private final Assignment cElevationChangeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cElevationChangeINTTerminalRuleCall_3_0 = (RuleCall)cElevationChangeAssignment_3.eContents().get(0);
		private final Assignment cAngleAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAngleSignedIntParserRuleCall_4_0 = (RuleCall)cAngleAssignment_4.eContents().get(0);
		
		//Track:
		//	"Track" name=ID length=INT elevationChange=INT? angle=SignedInt?;
		public ParserRule getRule() { return rule; }

		//"Track" name=ID length=INT elevationChange=INT? angle=SignedInt?
		public Group getGroup() { return cGroup; }

		//"Track"
		public Keyword getTrackKeyword_0() { return cTrackKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//length=INT
		public Assignment getLengthAssignment_2() { return cLengthAssignment_2; }

		//INT
		public RuleCall getLengthINTTerminalRuleCall_2_0() { return cLengthINTTerminalRuleCall_2_0; }

		//elevationChange=INT?
		public Assignment getElevationChangeAssignment_3() { return cElevationChangeAssignment_3; }

		//INT
		public RuleCall getElevationChangeINTTerminalRuleCall_3_0() { return cElevationChangeINTTerminalRuleCall_3_0; }

		//angle=SignedInt?
		public Assignment getAngleAssignment_4() { return cAngleAssignment_4; }

		//SignedInt
		public RuleCall getAngleSignedIntParserRuleCall_4_0() { return cAngleSignedIntParserRuleCall_4_0; }
	}

	public class CartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Cart");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Cart:
		//	"Cart" name=ID;
		public ParserRule getRule() { return rule; }

		//"Cart" name=ID
		public Group getGroup() { return cGroup; }

		//"Cart"
		public Keyword getCartKeyword_0() { return cCartKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}

	public class SignedIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SignedInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSignAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cSignHyphenMinusKeyword_0_0 = (Keyword)cSignAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//SignedInt:
		//	sign="-"? value=INT;
		public ParserRule getRule() { return rule; }

		//sign="-"? value=INT
		public Group getGroup() { return cGroup; }

		//sign="-"?
		public Assignment getSignAssignment_0() { return cSignAssignment_0; }

		//"-"
		public Keyword getSignHyphenMinusKeyword_0_0() { return cSignHyphenMinusKeyword_0_0; }

		//value=INT
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_1_0() { return cValueINTTerminalRuleCall_1_0; }
	}
	
	
	private ModelElements pModel;
	private RollerCoasterElements pRollerCoaster;
	private TrackElements pTrack;
	private CartElements pCart;
	private SignedIntElements pSignedInt;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public CoasterGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.rollercoaster.dsl.Coaster".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	rollerCoaster+=RollerCoaster;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//RollerCoaster:
	//	name=ID track+=Track* cart+=Cart*;
	public RollerCoasterElements getRollerCoasterAccess() {
		return (pRollerCoaster != null) ? pRollerCoaster : (pRollerCoaster = new RollerCoasterElements());
	}
	
	public ParserRule getRollerCoasterRule() {
		return getRollerCoasterAccess().getRule();
	}

	//Track:
	//	"Track" name=ID length=INT elevationChange=INT? angle=SignedInt?;
	public TrackElements getTrackAccess() {
		return (pTrack != null) ? pTrack : (pTrack = new TrackElements());
	}
	
	public ParserRule getTrackRule() {
		return getTrackAccess().getRule();
	}

	//Cart:
	//	"Cart" name=ID;
	public CartElements getCartAccess() {
		return (pCart != null) ? pCart : (pCart = new CartElements());
	}
	
	public ParserRule getCartRule() {
		return getCartAccess().getRule();
	}

	//SignedInt:
	//	sign="-"? value=INT;
	public SignedIntElements getSignedIntAccess() {
		return (pSignedInt != null) ? pSignedInt : (pSignedInt = new SignedIntElements());
	}
	
	public ParserRule getSignedIntRule() {
		return getSignedIntAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
