/*
 * generated by Xtext
 */
package org.xtext.rollercoaster.dsl.ui.contentassist

import org.xtext.rollercoaster.dsl.ui.contentassist.AbstractCoasterProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CoasterProposalProvider extends AbstractCoasterProposalProvider {
}
