/*
* generated by Xtext
*/
package org.xtext.rollercoaster.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CoasterUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.rollercoaster.dsl.ui.internal.CoasterActivator.getInstance().getInjector("org.xtext.rollercoaster.dsl.Coaster");
	}
	
}
