/*
 * generated by Xtext
 */
package org.xtext.rollercoaster.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CoasterRuntimeModule extends org.xtext.rollercoaster.dsl.AbstractCoasterRuntimeModule {

}
