/*
* generated by Xtext
*/
package org.xtext.rollercoaster.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CoasterStandaloneSetup extends CoasterStandaloneSetupGenerated{

	public static void doSetup() {
		new CoasterStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

