/*
 * generated by Xtext
 */
package org.xtext.rollercoaster.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CoasterUiModule extends org.xtext.rollercoaster.dsl.ui.AbstractCoasterUiModule {
	public CoasterUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
